# handlers file for supervisor
---
- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  register: superviosr-restarted
  when: service_default_state | default('started') == 'started'

- name: reload supervisor config
  command: supervisorctl update all
  when: 
    - service_default_state | default('started') == 'started'
    - supervisor-restarted is not defined
